backend:
  name: git-gateway
  #repo: https://github.com/SsempogoEzra/DecapTest/ # <-- Double check this is correct!
  branch: main # <-- If your GitHub says 'master', change this to master

media_folder: "./images/uploads"
public_folder: "/images/uploads"

collections:
collections:
  - name: "safari_list"
    label: "Safari Management"
    files:
      - label: "All Safari Packages"
        name: "packages"
        file: "data/safaris.json"
        fields:
          - label: "Safaris"
            name: "safaris"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Duration", name: "duration", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Featured Image", name: "image", widget: "image"}}